### https://youtu.be/RcxvrhQKv8I?t=325 great tutorial
### used both json and encoded url data
### be sure to kill all processes in vscode after laptop sleep, otherwise https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

@hostname = http://localhost:5000/api/blogs

GET {{hostname}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGZlZDgyYjRiZmRiNDIyZmFmOTAwOSIsImlhdCI6MTY3ODgyNTY0OCwiZXhwIjoxNjgxNDE3NjQ4fQ.9abdma_cJ7Z6rBD0Ds91lXLKr231csn83zH-qV0XLro

### 

POST {{hostname}}
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGZlZDgyYjRiZmRiNDIyZmFmOTAwOSIsImlhdCI6MTY3ODgyMzk2OSwiZXhwIjoxNjgxNDE1OTY5fQ.WK99RUkajNJvpeO-gLJevM4YwC9ozCICdDriVCGVYXQ

text=my first vlog 3

### 640eb200d49af222aec3d436

PUT {{hostname}}/640eb200d49af222aec3d436
Content-Type: application/json
Authorization: Bearer

{
  "text": "hello world!"
}

### 6410d9ab94364450e1255d57

DELETE {{hostname}}/6410daedb4cf9f4fd2e92c53
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGZlZDgyYjRiZmRiNDIyZmFmOTAwOSIsImlhdCI6MTY3ODg0MTcyMCwiZXhwIjoxNjgxNDMzNzIwfQ.6Vzj-e7nQb1RqpsXRsLu9mUFsgyBK3yJnHqg6DG6IkA

### 

GET {{hostname}}
Content-Type: application/x-www-form-urlencoded


### MUST HAVE A new line after "Content-Type" otherwise
### "Headername must be a valid HTTP token..." error

POST {{hostname}}
Content-Type: application/x-www-form-urlencoded

test=some other data
