### https://youtu.be/RcxvrhQKv8I?t=325 great tutorial
### used both json and encoded url data
@hostname = http://localhost:5000/api/goals

GET {{hostname}}
Content-Type: application/json
Authorization: {{apiKey}}

### 

POST {{hostname}}
Content-Type: application/json

###

PUT {{hostname}}/112312
Content-Type: application/json

{
  "message": "hello world!"
}

###

DELETE {{hostname}}/1
Content-Type: application/json

{
  "message": "hello world!"
}

### 

GET {{hostname}}
Content-Type: application/x-www-form-urlencoded

test=some data

### MUST HAVE A new line after "Content-Type" otherwise
### "Headername must be a valid HTTP token..." error

POST {{hostname}}
Content-Type: application/x-www-form-urlencoded

test=some other data
